name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docs-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install and run tfplugindocs CLI
        run: |
          mkdir downloads
          cd downloads
          wget https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.5.0/tfplugindocs_0.5.0_linux_amd64.zip
          unzip tfplugindocs_0.5.0_linux_amd64.zip
          cd ..
          mv downloads/tfplugindocs .
          ./tfplugindocs generate
          rm -rf ./tfplugindocs downloads
      
      - name: Install and run auto-changelog CLI
        run: |
          npm i -g auto-changelog@2.3.0
          auto-changelog --config=.auto-changelog-config
      
      - name: Add and commit generated docs and CHANGELOG.md
        uses: test-room-7/action-update-file@v1
        with:
          branch: master
          commit-msg: Update docs and CHANGELOG.md
          file-path: |
            docs/**/*.md
            examples/**/*.tf
            examples/**/*.sh
            CHANGELOG.md
          github-token: ${{ secrets.GHTOKEN }}
  
  goreleaser:
    needs: docs-and-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Pull latest changes (docs and CHANGELOG.md)
        run: git pull
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
